token-core/tcx/src/handler.rs
token-core/tcx/src/migration.rs
token-core/tcx/tests/migration_test.rs

When migrating a keystore, a _migrated.json file is generated to store the mapping between the migrated file ID and the original file ID.
When deleting a wallet, the corresponding mapping is found and the original keystore is also deleted. If the _migrated.json file is empty, it is also deleted.

delete all associated keystore when delete_keystore is called

---

imkey-core/ikc-common/src/path.rs
imkey-core/ikc-proto/src/api.proto
imkey-core/ikc-proto/src/btc.proto
imkey-core/ikc-wallet/coin-bitcoin/src/btcapi.rs
imkey-core/ikc-wallet/coin-substrate/src/address.rs
imkey-core/ikc/src/api.rs
imkey-core/ikc/src/btc_address.rs
imkey-core/ikc/src/handler.rs
imkey-core/ikc/src/lib.rs

- add get_extended_public_key feature
- add get_extended_public_key test case

feat: ikc add get_extended_public_key api [R2D2-10567]

---

token-core/tcx-proto/src/params.proto
token-core/tcx/src/api.rs
token-core/tcx/src/migration.rs
token-core/tcx/tests/migration_test.rs

- MigrateKeystoreParam adds network field
- modify migration related test cases

feat: migrate add network field

---

imkey-core/ikc/src/ethereum_signer.rs
token-core/tcx-eth/src/signer.rs

- Append zero address when EthTxInput's to is empty

fix: sign eth empty address

---

token-core/tcx-keystore/src/identity.rs
token-core/tcx-migration/src/legacy_ipfs.rs
token-core/tcx-migration/src/lib.rs
token-core/tcx/src/handler.rs
token-core/tcx/tests/other_test.rs

- decrypt ipfs data using legacy enc key in identity.json before identity migration

fix: using legacy enc key

---

token-core/tcx-migration/src/migration.rs
token-core/tcx/src/migration.rs
token-core/tcx/tests/migration_test.rs
token-core/test-data/wallets/0d49aae6-cf73-4ebb-998d-b6312d18361f.json
token-core/test-data/wallets/20a9f050-7fd1-4f2c-b7f8-f03c78201f78.json

- fix cannot migrate old private key eos keystore

fix: cannot migrate old private key eos keystore

---

token-core/tcx-migration/src/migration.rs
token-core/test-data/wallets/20a9f050-7fd1-4f2c-b7f8-f03c78201f78.json

-  cannot migrate old private key ios eos keystore

fix: cannot migrate old private key ios eos keystore

---

token-core/tcx-eth/src/signer.rs
token-core/tcx/tests/sign_test.rs

- eth_sign need to sign raw data

fix: eth_sign need to sign raw data

---

token-core/tcx/src/handler.rs
token-core/tcx/src/migration.rs
token-core/tcx/tests/migration_test.rs
token-core/test-data/migrate-duplication-fixtures/wallets/792a0051-16d7-44a7-921a-9b4a0c893b8f

- fix not remove old ks in memory

fix: remove old ks in memory

---

token-core/tcx/src/migration.rs
token-core/tcx/tests/migration_test.rs

1. Fixed the problem of deleting all keystores whose source ends with _IDENTITY when deleting the keystore under identity.
2. add relevant test cases

fix: fix identity keystore delete bug[R2D2-10888]

---

Cargo.lock
imkey-core/ikc/src/handler.rs
imkey-core/ikc/src/lib.rs
token-core/tcx/Cargo.toml
token-core/tcx/src/migration.rs

- Add checksum to the eth address returned by the scan_legacy_keystores interface
- Modify related test cases

chore: return eth address add checksum

---

token-core/tcx-keystore/src/keystore/hd.rs
token-core/tcx-keystore/src/keystore/mod.rs
token-core/tcx-migration/src/keystore_upgrade.rs
token-core/tcx-migration/src/migration.rs
token-core/tcx-migration/tests/fixtures/6f8c2912-ebe8-4359-90f4-f1d1f1af1e4d
token-core/tcx/src/handler.rs
token-core/tcx/tests/import_test.rs

fix: throw error when keystore metadata missing passwordHint field

fix: metadata missing password_hint error

---

imkey-core/ikc-wallet/coin-cosmos/src/transaction.rs

fix  ikc cosmos signature error

fix: ikc cosmos signature error

---

.github/workflows/build-release-ios.yml
imkey-core/ikc-common/src/constants.rs
imkey-core/ikc-device/src/device_binding.rs
imkey-core/ikc-wallet/coin-cosmos/src/transaction.rs
publish/android/.idea/compiler.xml
publish/android/.idea/gradle.xml
publish/android/.idea/misc.xml
publish/android/build.gradle
publish/android/gradle/wrapper/gradle-wrapper.properties
publish/android/tokencore/build.gradle
script/build-android.sh

Set the timeout time to 120s when binding imKey
jira：https://imtoken.atlassian.net/browse/R2D2-10958

feat: reset bind timeout time and fix CI error

---

token-core/tcx/src/handler.rs
token-core/tcx/tests/import_test.rs

- assert the target wallet before search existed wallet
https://imtoken.atlassian.net/browse/R2D2-11396
- Check if the packaged keystore has been uploaded …

fix: assert overwrite wallet first

---

Cargo.lock
token-core/tcx-migration/Cargo.toml

remove useless serde-aux library

chore: remove useless serde-aux library[R2D2-11498]

---

Cargo.lock
token-core/tcx-atom/Cargo.toml
token-core/tcx-atom/src/address.rs
token-core/tcx-atom/src/signer.rs
token-core/tcx-btc-kin/src/address.rs
token-core/tcx-btc-kin/src/bch_address.rs
token-core/tcx-btc-kin/src/message.rs
token-core/tcx-btc-kin/src/psbt.rs
token-core/tcx-btc-kin/src/signer.rs
token-core/tcx-ckb/src/address.rs
token-core/tcx-ckb/src/signer.rs
token-core/tcx-constants/src/btc_fork_network.rs
token-core/tcx-constants/src/coin_info.rs
token-core/tcx-docs/INTEGRATION.md
token-core/tcx-eth/src/address.rs
token-core/tcx-filecoin/src/address.rs
token-core/tcx-keystore/src/keystore/hd.rs
token-core/tcx-keystore/src/keystore/mod.rs
token-core/tcx-keystore/src/keystore/private.rs
token-core/tcx-migration/src/migration.rs
token-core/tcx-proto/src/params.proto
token-core/tcx-substrate/src/address.rs
token-core/tcx-tezos/src/address.rs
token-core/tcx-tron/src/address.rs
token-core/tcx/src/api.rs
token-core/tcx/src/handler.rs
token-core/tcx/src/reset_password.rs
token-core/tcx/tests/derive_test.rs

- embed top 15 chain id and hrp mapping of cosmos, verify when user derive account

feat: add top 15 chain_id and hrp verified

---

imkey-core/ikc-proto/src/api.proto
imkey-core/ikc/src/api.rs
imkey-core/ikc/src/handler.rs
imkey-core/ikc/src/lib.rs

- remove unused bech32Prefix param

fix: remove bech32_prefix from ikc

---

imkey-core/ikc-device/src/device_binding.rs
imkey-core/ikc-device/src/device_manager.rs
imkey-core/ikc-wallet/coin-bitcoin/src/transaction.rs
imkey-core/ikc/src/lib.rs

…when btc not upgraded
fixed the issue of Legacy and Nested Segwit transaction failure.

fix: fixed the issue of Legacy and Nested Segwit transaction failure [R2D2-12387]

---

imkey-core/ikc-proto/src/tron.proto
imkey-core/ikc-wallet/coin-tron/src/signer.rs
imkey-core/ikc-wallet/coin-tron/src/tronapi.rs
token-core/tcx-proto/src/tron.proto
token-core/tcx-tron/src/signer.rs
token-core/tcx-tron/src/transaction.rs
token-core/tcx/tests/sign_test.rs

tron sign message support v2 version

feat: tron sign message support v2 version[R2D2-11852]

---

token-core/tcx/src/handler.rs
token-core/tcx/src/migration.rs

当 key 为 null，抛出 need_password_or_derived_key 的错误信息.

raise need_password_or_derived_key when key is null

---

.github/workflows/build-release-android.yml
.github/workflows/build-release-ios.yml
.github/workflows/run-unittest.yml
imkey-core/ikc-common/src/apdu.rs
imkey-core/ikc-common/src/constants.rs
imkey-core/ikc-common/src/error.rs
imkey-core/ikc-wallet/coin-bitcoin/src/transaction.rs

ikc add upgrade_applet error info

chore: ikc add upgrade_applet error info[OPS-3225]

---

Cargo.lock
token-core/tcx/Cargo.toml
token-core/tcx/src/handler.rs
token-core/tcx/tests/import_test.rs

optimize the error prompt of importing private key[R2D2-14129]

chore: optimize the error prompt of importing private key[R2D2-14129]
